import Head from "next/head";
import Script from "next/script";
import Calculadora from "./components/Calculadora";

export default function Home() {
  return (
    <>
      <Head>
        <title>#boracodar | Calculadora</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Calculadora />
      </main>
      <Script>document.querySelector</Script>
    </>
  );
}
