import Head from "next/head";
import Image from "next/image";
import Calculadora from "./components/Calculadora";

export default function Home() {
  return (
    <>
      <Head>
        <title>#boracodar | Calculadora</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Calculadora />
      </main>
    </>
  );
}
